# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abe7b13024526bd157dc7fa034f9c5ce4fbdf12dcc481be81340029956dfdccc69d783d84ed1374065fbd78bc675f90f4c7b63ef9542c2b5dce5b093d68b3475

test:
  secret_key_base: d2bb1d15e9ed65bee62d9aaec3ddc1601fc0136d4f54c17e22a354eb6d26a3dc0dc94fb0290519fa143eab181c4cf8bdefbc2df231db7ed7c581977e5d7136b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
